### PR TITLE
Feature/cbcheck: couchbase health check

### PR DESCRIPTION
**Pull request by innovatechs**
Doug, a very important remaining point during the install is the following:

setup.py: add dependency in the /usr/lib/systemd/system/oxauth.service
After=cbcheck.service

### CODE REVIEW

**Comment by harrdou** [comment]
> Doug, a very important remaining point during the install is the following:
> 
> setup.py: add dependency in the /usr/lib/systemd/system/oxauth.service
> After=cbcheck.service

Not needed, as the new unit file already specifies `Before=oxauth.service`

**Comment by harrdou** [comment]
Only minor tweak is to change the Couchbase userid from "Administrator" to "gluu". I can do that.

**Comment by harrdou** [comment]
> Only minor tweak is to change the Couchbase userid from "Administrator" to "gluu". I can do that.

On second thought I've got a better idea. Instead of hard coding the userid, grab the value of `auth.userName` from `gluu-couchbase.properties`.

**Comment by innovatechs** [comment]
> > Doug, a very important remaining point during the install is the following:
> > setup.py: add dependency in the /usr/lib/systemd/system/oxauth.service
> > After=cbcheck.service
> 
> Not needed, as the new unit file already specifies `Before=oxauth.service`

I agree with you ! Thanks

**Review by vid — APPROVED** [review]

**Review by harrdou — APPROVED** [review]

**Pull request merged**
