### PR TITLE
Feature/enhance telemetry

### PR DESCRIPTION
**Pull request by innovatechs**
Collects additional telemetry so that we can report on:

For new users:
- Which client is the new user registering to sign in for?
- How many choose GCKey and how many choose Interac?

For exiting users:
- How many existing users signed in to a new client.

### CODE REVIEW

**Comment by wmoussa-gc** [comment]
should we close this? @innovatechs  @harrdou

**Comment by innovatechs** [comment]
> should we close this? @innovatechs @harrdou

This is a new feature which is not yet integrated into the develop branch. We usually keep those features open until we do the merge.

**Comment by wmoussa-gc** [comment]
I recommend we close this PR if we're not actively working on it (i.e. has been prioritized by the team for the sprint). The feature/enhanceTelemetry branch is still there and we can re-open a new PR if needed. would that work?

**Comment by innovatechs** [comment]
> I recommend we close this PR if we're not actively working on it (i.e. has been prioritized by the team for the sprint). The feature/enhanceTelemetry branch is still there and we can re-open a new PR if needed. would that work?

That works for me. @harrdou ?

**Comment by harrdou** [comment]
I've updated the PR description to better explain what this is about. This enhancement was mostly driven by client request for more information about their user' choices.

With the new UX telemetry recently added to release 1.3.x, we now know track how many users choose to sign in with GCKey vs Interac, but not on a per-client basis and we don't distinguish between new and existing users.

The number of users who have registered with more than one client can be determined now at the sector level by querying the database, but cannot be determined at the individual client level. Recording these events in Azure Monitor  was just to make the data more accessible via Application Insights.

**Comment by harrdou** [comment]
@wmoussa-gc , I'm in agreement we can close the PR and keep the branch around.

**Comment by wmoussa-gc** [comment]
created an issue to track https://github.com/sign-in-canada/Acceptance-Platform/issues/142

**Pull request closed without merging**
