### PR TITLE
Fix AB#7566

### PR DESCRIPTION
**Pull request by innovatechs**

### CODE REVIEW

**Review by harrdou — CHANGES_REQUESTED** [review]
Oops. Sorry, your PR is requesting merge into the wrong branch (main instead of develop).

I'll close the RP and create a new one,

**Comment by harrdou** [comment]
Wrong branch.

**Comment by innovatechs** [comment]
Sorry for that, I thought the hotfixes (severe bugs) should be merged into main (based on SIC gitflow).

**Comment by harrdou** [comment]
This is a minor bug.

**Pull request closed without merging**
